In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime, time


from scipy.stats import shapiro, kstest
from scipy.stats import ttest_ind, ttest_1samp, ttest_rel, f_oneway
from scipy.stats import mannwhitneyu, kruskal, wilcoxon, normaltest

In [2]:
redcomm = pd.read_csv("Social Media - Redcomm - Sheet1.csv")
redcomm = pd.DataFrame(redcomm)

In [3]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2/20/23 14:00,"Serial yang diangkat dari kisah nyata, tentang...","10,865",71,15.0,134.0,"11,085","1,424","2,372,168","3,392,200",Reels,Netflixid
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2/20/23 12:00,"?? Begini nasib, jadi third wheeler~","2,588",21,26.0,91.0,"2,726","1,739","466,859","840,346",Videos,Netflixid
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2/20/23 10:00,"Udah akrab gini, apakah Jae-woo bakal berujung...","1,494",14,113.0,67.0,"1,688",0,"190,069","334,521",Picture,Netflixid
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2/20/23 8:00,Diajak main Alphabet Challenge pake huruf D-E-...,"1,271",10,39.0,NaN,"1,405","1,409","314,446","455,947",Reels,Netflixid
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2/20/23 6:00,Besok kita buka bareng-bareng gaes suratnya!,"19,829",412,91.0,117.0,"20,449",0,"1,518,338","2,307,874",Carousels,Netflixid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,1/1/22 12:01,NaN,"2,446",37,188.0,54.0,"2,725","2,070","607,498","807,972",Videos,Netflixid
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,1/1/22 10:00,NaN,"10,223",147,76.0,97.0,"10,543","1,114","1,475,764","2,316,949",Reels,Netflixid
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,1/1/22 8:00,NaN,"10,125",52,4.0,96.0,"10,277",0,"1,095,117","1,445,554",Carousels,Netflixid
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,1/1/22 6:00,NaN,"24,190",159,88.0,108.0,"24,545","1,761","4,601,342","5,889,718",Videos,Netflixid
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,1/1/22 4:00,NaN,"14,006",62,190.0,19.0,"14,277","1,454","1,752,248","2,312,967",Reels,Netflixid

In [4]:
redcomm.isna().sum()

id                   0
ingestion_date       0
link                 0
date                 1
post_message      2328
like                 2
comments             4
saved                7
share                5
engagement           1
video_views          0
reach                0
impression           0
type                 0
username             0
dtype: int64

In [5]:
# CHECK DATA TYPES
redcomm.dtypes

id                  int64
ingestion_date     object
link               object
date               object
post_message       object
like               object
comments           object
saved             float64
share             float64
engagement         object
video_views        object
reach              object
impression         object
type               object
username           object
dtype: object

In [6]:
# CONVERT date's object to datetime
redcomm['date'] = pd.to_datetime(redcomm['date'], errors='coerce')

C:\Users\Andreas Hoffman P\AppData\Local\Temp\ipykernel_10048\2968553512.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  redcomm['date'] = pd.to_datetime(redcomm['date'], errors='coerce')

In [7]:
redcomm.dtypes

id                         int64
ingestion_date            object
link                      object
date              datetime64[ns]
post_message              object
like                      object
comments                  object
saved                    float64
share                    float64
engagement                object
video_views               object
reach                     object
impression                object
type                      object
username                  object
dtype: object

In [8]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...","10,865",71,15.0,134.0,"11,085","1,424","2,372,168","3,392,200",Reels,Netflixid
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~","2,588",21,26.0,91.0,"2,726","1,739","466,859","840,346",Videos,Netflixid
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...","1,494",14,113.0,67.0,"1,688",0,"190,069","334,521",Picture,Netflixid
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,"1,271",10,39.0,NaN,"1,405","1,409","314,446","455,947",Reels,Netflixid
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,"19,829",412,91.0,117.0,"20,449",0,"1,518,338","2,307,874",Carousels,Netflixid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,"2,446",37,188.0,54.0,"2,725","2,070","607,498","807,972",Videos,Netflixid
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,"10,223",147,76.0,97.0,"10,543","1,114","1,475,764","2,316,949",Reels,Netflixid
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,"10,125",52,4.0,96.0,"10,277",0,"1,095,117","1,445,554",Carousels,Netflixid
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,"24,190",159,88.0,108.0,"24,545","1,761","4,601,342","5,889,718",Videos,Netflixid
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,"14,006",62,190.0,19.0,"14,277","1,454","1,752,248","2,312,967",Reels,Netflixid

MENGUBAH SEJUMLAH OBJECT MENJADI NUMERIC

In [9]:
# CHANGE OBJECTS to NUMERIC

redcomm['like'] = pd.to_numeric(redcomm['like'].str.replace(',',''), errors='coerce')

In [10]:
redcomm.dtypes

id                         int64
ingestion_date            object
link                      object
date              datetime64[ns]
post_message              object
like                     float64
comments                  object
saved                    float64
share                    float64
engagement                object
video_views               object
reach                     object
impression                object
type                      object
username                  object
dtype: object

In [11]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...",10865.0,71,15.0,134.0,"11,085","1,424","2,372,168","3,392,200",Reels,Netflixid
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~",2588.0,21,26.0,91.0,"2,726","1,739","466,859","840,346",Videos,Netflixid
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...",1494.0,14,113.0,67.0,"1,688",0,"190,069","334,521",Picture,Netflixid
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,1271.0,10,39.0,NaN,"1,405","1,409","314,446","455,947",Reels,Netflixid
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,19829.0,412,91.0,117.0,"20,449",0,"1,518,338","2,307,874",Carousels,Netflixid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,2446.0,37,188.0,54.0,"2,725","2,070","607,498","807,972",Videos,Netflixid
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,10223.0,147,76.0,97.0,"10,543","1,114","1,475,764","2,316,949",Reels,Netflixid
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,10125.0,52,4.0,96.0,"10,277",0,"1,095,117","1,445,554",Carousels,Netflixid
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,24190.0,159,88.0,108.0,"24,545","1,761","4,601,342","5,889,718",Videos,Netflixid
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,14006.0,62,190.0,19.0,"14,277","1,454","1,752,248","2,312,967",Reels,Netflixid

In [12]:
redcomm['comments'] = pd.to_numeric(redcomm['comments'], errors='coerce')
redcomm['saved'] = pd.to_numeric(redcomm['saved'], errors='coerce')
redcomm['engagement'] = pd.to_numeric(redcomm['engagement'].str.replace(',',''), errors='coerce')
redcomm['video_views'] = pd.to_numeric(redcomm['video_views'].str.replace(',',''), errors='coerce')
redcomm['reach'] = pd.to_numeric(redcomm['reach'].str.replace(',',''), errors='coerce')
redcomm['impression'] = pd.to_numeric(redcomm['impression'].str.replace(',',''), errors='coerce')

In [13]:
redcomm.dtypes

id                         int64
ingestion_date            object
link                      object
date              datetime64[ns]
post_message              object
like                     float64
comments                 float64
saved                    float64
share                    float64
engagement               float64
video_views                int64
reach                      int64
impression                 int64
type                      object
username                  object
dtype: object

In [14]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...",10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200,Reels,Netflixid
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~",2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346,Videos,Netflixid
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...",1494.0,14.0,113.0,67.0,1688.0,0,190069,334521,Picture,Netflixid
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947,Reels,Netflixid
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874,Carousels,Netflixid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972,Videos,Netflixid
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949,Reels,Netflixid
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554,Carousels,Netflixid
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718,Videos,Netflixid
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967,Reels,Netflixid

SET KOLOM DAY DAN MONTH

In [15]:
redcomm['day'] = redcomm['date'].dt.day_name()
redcomm['month'] = redcomm['date'].dt.month

In [16]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username,day,month
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...",10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200,Reels,Netflixid,Monday,2.0
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~",2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346,Videos,Netflixid,Monday,2.0
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...",1494.0,14.0,113.0,67.0,1688.0,0,190069,334521,Picture,Netflixid,Monday,2.0
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947,Reels,Netflixid,Monday,2.0
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874,Carousels,Netflixid,Monday,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972,Videos,Netflixid,Saturday,1.0
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949,Reels,Netflixid,Saturday,1.0
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554,Carousels,Netflixid,Saturday,1.0
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718,Videos,Netflixid,Saturday,1.0
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967,Reels,Netflixid,Saturday,1.0

SET KOLOM TIME UNTUK SETUP INTERVAL PERIODE HARI: Midnight, Morning, Afternoon, Evening, Night

In [17]:
redcomm['time']=pd.to_datetime(redcomm['date'], errors='coerce').dt.time

In [18]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username,day,month,time
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...",10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200,Reels,Netflixid,Monday,2.0,14:00:00
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~",2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346,Videos,Netflixid,Monday,2.0,12:00:00
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...",1494.0,14.0,113.0,67.0,1688.0,0,190069,334521,Picture,Netflixid,Monday,2.0,10:00:00
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947,Reels,Netflixid,Monday,2.0,08:00:00
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874,Carousels,Netflixid,Monday,2.0,06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972,Videos,Netflixid,Saturday,1.0,12:01:00
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949,Reels,Netflixid,Saturday,1.0,10:00:00
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554,Carousels,Netflixid,Saturday,1.0,08:00:00
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718,Videos,Netflixid,Saturday,1.0,06:00:00
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967,Reels,Netflixid,Saturday,1.0,04:00:00

In [19]:
redcomm.dtypes

id                         int64
ingestion_date            object
link                      object
date              datetime64[ns]
post_message              object
like                     float64
comments                 float64
saved                    float64
share                    float64
engagement               float64
video_views                int64
reach                      int64
impression                 int64
type                      object
username                  object
day                       object
month                    float64
time                      object
dtype: object

In [20]:
redcomm['hour']= pd.to_datetime(redcomm['date']).dt.hour

In [21]:
redcomm.dtypes

id                         int64
ingestion_date            object
link                      object
date              datetime64[ns]
post_message              object
like                     float64
comments                 float64
saved                    float64
share                    float64
engagement               float64
video_views                int64
reach                      int64
impression                 int64
type                      object
username                  object
day                       object
month                    float64
time                      object
hour                     float64
dtype: object

In [22]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username,day,month,time,hour
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...",10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200,Reels,Netflixid,Monday,2.0,14:00:00,14.0
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~",2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346,Videos,Netflixid,Monday,2.0,12:00:00,12.0
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...",1494.0,14.0,113.0,67.0,1688.0,0,190069,334521,Picture,Netflixid,Monday,2.0,10:00:00,10.0
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947,Reels,Netflixid,Monday,2.0,08:00:00,8.0
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874,Carousels,Netflixid,Monday,2.0,06:00:00,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972,Videos,Netflixid,Saturday,1.0,12:01:00,12.0
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949,Reels,Netflixid,Saturday,1.0,10:00:00,10.0
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554,Carousels,Netflixid,Saturday,1.0,08:00:00,8.0
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718,Videos,Netflixid,Saturday,1.0,06:00:00,6.0
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967,Reels,Netflixid,Saturday,1.0,04:00:00,4.0

PEMBAGIAN INTERVAL WAKTU

In [23]:
# PEMBAGIAN INTERVAL WAKTU

interval_hour = [0, 6, 12, 18, 24]
labels = ['Midnight', 'Morning', 'Afternoon', 'Evening']

redcomm['period'] = pd.cut(redcomm['hour'], bins=interval_hour, labels=labels, include_lowest=True, right=False)

In [24]:
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,video_views,reach,impression,type,username,day,month,time,hour,period
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...",10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200,Reels,Netflixid,Monday,2.0,14:00:00,14.0,Afternoon
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~",2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346,Videos,Netflixid,Monday,2.0,12:00:00,12.0,Afternoon
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...",1494.0,14.0,113.0,67.0,1688.0,0,190069,334521,Picture,Netflixid,Monday,2.0,10:00:00,10.0,Morning
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947,Reels,Netflixid,Monday,2.0,08:00:00,8.0,Morning
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874,Carousels,Netflixid,Monday,2.0,06:00:00,6.0,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972,Videos,Netflixid,Saturday,1.0,12:01:00,12.0,Afternoon
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949,Reels,Netflixid,Saturday,1.0,10:00:00,10.0,Morning
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554,Carousels,Netflixid,Saturday,1.0,08:00:00,8.0,Morning
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718,Videos,Netflixid,Saturday,1.0,06:00:00,6.0,Morning
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967,Reels,Netflixid,Saturday,1.0,04:00:00,4.0,Midnight

KOLOM TAHUN

In [25]:
redcomm['year']= pd.to_datetime(redcomm['date']).dt.year
redcomm

,id,ingestion_date,link,date,post_message,like,comments,saved,share,engagement,...,reach,impression,type,username,day,month,time,hour,period,year
0,8495879833,25 May 2023,https://www.instagram.com/p/Co4wPXXJjku/,2023-02-20 14:00:00,"Serial yang diangkat dari kisah nyata, tentang...",10865.0,71.0,15.0,134.0,11085.0,...,2372168,3392200,Reels,Netflixid,Monday,2.0,14:00:00,14.0,Afternoon,2023.0
1,8495879833,25 May 2023,https://www.instagram.com/p/Co4ihdsJevl/,2023-02-20 12:00:00,"?? Begini nasib, jadi third wheeler~",2588.0,21.0,26.0,91.0,2726.0,...,466859,840346,Videos,Netflixid,Monday,2.0,12:00:00,12.0,Afternoon,2023.0
2,8495879833,25 May 2023,https://www.instagram.com/reel/Co4UwKhp1uw/,2023-02-20 10:00:00,"Udah akrab gini, apakah Jae-woo bakal berujung...",1494.0,14.0,113.0,67.0,1688.0,...,190069,334521,Picture,Netflixid,Monday,2.0,10:00:00,10.0,Morning,2023.0
3,8495879833,25 May 2023,https://www.instagram.com/reel/Co4HBkaJm_Y/,2023-02-20 08:00:00,Diajak main Alphabet Challenge pake huruf D-E-...,1271.0,10.0,39.0,NaN,1405.0,...,314446,455947,Reels,Netflixid,Monday,2.0,08:00:00,8.0,Morning,2023.0
4,8495879833,25 May 2023,https://www.instagram.com/p/Co35ZDtJYai/,2023-02-20 06:00:00,Besok kita buka bareng-bareng gaes suratnya!,19829.0,412.0,91.0,117.0,20449.0,...,1518338,2307874,Carousels,Netflixid,Monday,2.0,06:00:00,6.0,Morning,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,8495879833,25 May 2023,https://www.instagram.com/tv/CYL8r6hBIIN/,2022-01-01 12:01:00,NaN,2446.0,37.0,188.0,54.0,2725.0,...,607498,807972,Videos,Netflixid,Saturday,1.0,12:01:00,12.0,Afternoon,2022.0
2609,8495879833,25 May 2023,https://www.instagram.com/p/CYLu8Cxpu36/,2022-01-01 10:00:00,NaN,10223.0,147.0,76.0,97.0,10543.0,...,1475764,2316949,Reels,Netflixid,Saturday,1.0,10:00:00,10.0,Morning,2022.0
2610,8495879833,25 May 2023,https://www.instagram.com/p/CYLhM0xhueX/,2022-01-01 08:00:00,NaN,10125.0,52.0,4.0,96.0,10277.0,...,1095117,1445554,Carousels,Netflixid,Saturday,1.0,08:00:00,8.0,Morning,2022.0
2611,8495879833,25 May 2023,https://www.instagram.com/p/CYLTblPJ-p4/,2022-01-01 06:00:00,NaN,24190.0,159.0,88.0,108.0,24545.0,...,4601342,5889718,Videos,Netflixid,Saturday,1.0,06:00:00,6.0,Morning,2022.0
2612,8495879833,25 May 2023,https://www.instagram.com/p/CYLFwKhs6T2/,2022-01-01 04:00:00,NaN,14006.0,62.0,190.0,19.0,14277.0,...,1752248,2312967,Reels,Netflixid,Saturday,1.0,04:00:00,4.0,Midnight,2022.0

ENGAGEMENT HARIAN

In [26]:
redcomm_daily = redcomm[['day', 'like', 'comments', 'saved', 'share', 'engagement', 'video_views', 'reach', 'impression']]
redcomm_daily

,day,like,comments,saved,share,engagement,video_views,reach,impression
0,Monday,10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200
1,Monday,2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346
2,Monday,1494.0,14.0,113.0,67.0,1688.0,0,190069,334521
3,Monday,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947
4,Monday,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874
...,...,...,...,...,...,...,...,...,...
2608,Saturday,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972
2609,Saturday,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949
2610,Saturday,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554
2611,Saturday,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718
2612,Saturday,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967

In [57]:
engagedaily = pd.DataFrame(redcomm_daily.groupby('day')[['engagement', 'reach', 'impression', 'like']].mean())
dayorder = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
redcomm_daily['day'] = pd.Categorical(redcomm_daily['day'], categories=dayorder, ordered=True)
engagedaily = engagedaily.sort_values(by='day')
engagedaily

C:\Users\Andreas Hoffman P\AppData\Local\Temp\ipykernel_10048\2517306359.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  redcomm_daily['day'] = pd.Categorical(redcomm_daily['day'], categories=dayorder, ordered=True)

             engagement         reach    impression          like
day
Monday     13705.616337  1.802381e+06  2.840282e+06  13312.483951
Tuesday    13300.616915  1.752283e+06  2.828657e+06  12912.259352
Wednesday  12730.390000  1.645580e+06  2.695613e+06  12337.847500
Thursday   12855.448363  1.671821e+06  2.708683e+06  12458.690176
Friday     12195.200489  1.655433e+06  2.663306e+06  11816.564792
Saturday    9476.500000  1.301608e+06  2.077875e+06   9148.700617
Sunday      9403.360000  1.178027e+06  1.862570e+06   9095.306569

ENGAGEMENT BERDASARKAN PERIOD

In [31]:
redcomm_period = redcomm[['period', 'like', 'comments', 'saved', 'share', 'engagement', 'video_views', 'reach', 'impression']]
redcomm_period

,period,like,comments,saved,share,engagement,video_views,reach,impression
0,Afternoon,10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200
1,Afternoon,2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346
2,Morning,1494.0,14.0,113.0,67.0,1688.0,0,190069,334521
3,Morning,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947
4,Morning,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874
...,...,...,...,...,...,...,...,...,...
2608,Afternoon,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972
2609,Morning,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949
2610,Morning,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554
2611,Morning,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718
2612,Midnight,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967

In [54]:
engageperiod = pd.DataFrame(redcomm_period.groupby('period')[['engagement', 'reach', 'impression', 'like']].mean())
engageperiod

             engagement         reach    impression          like
period
Midnight   13421.255627  1.796587e+06  2.859943e+06  13023.136656
Morning    11757.085253  1.492982e+06  2.398316e+06  11394.052308
Afternoon  11743.940320  1.624619e+06  2.637013e+06  11376.773256
Evening             NaN           NaN           NaN           NaN

STATISTIKA ENGAGEMENT 2023 DAN 2022

In [32]:
redcomm_2023 = redcomm[['month', 'period', 'like', 'comments', 'saved', 'share', 'engagement', 'video_views', 'reach', 'impression']][redcomm['year']==2023]
redcomm_2023

,month,period,like,comments,saved,share,engagement,video_views,reach,impression
0,2.0,Afternoon,10865.0,71.0,15.0,134.0,11085.0,1424,2372168,3392200
1,2.0,Afternoon,2588.0,21.0,26.0,91.0,2726.0,1739,466859,840346
2,2.0,Morning,1494.0,14.0,113.0,67.0,1688.0,0,190069,334521
3,2.0,Morning,1271.0,10.0,39.0,NaN,1405.0,1409,314446,455947
4,2.0,Morning,19829.0,412.0,91.0,117.0,20449.0,0,1518338,2307874
...,...,...,...,...,...,...,...,...,...,...
313,1.0,Afternoon,13761.0,131.0,117.0,139.0,14148.0,0,2507309,3961548
314,1.0,Morning,8049.0,105.0,19.0,133.0,8306.0,0,1492754,2582464
315,1.0,Morning,5293.0,31.0,43.0,95.0,5462.0,0,411944,749738
316,1.0,Morning,7237.0,177.0,140.0,172.0,7726.0,2450,528545,734678
317,1.0,Midnight,24932.0,197.0,170.0,102.0,25401.0,1714,4501236,7832151

In [51]:
## ENGAGEMENT AVG 2023
engage2023 = pd.DataFrame(redcomm_2023.groupby('month')[['engagement', 'reach', 'impression', 'like']].mean())
engage2023

         engagement         reach    impression          like
month
1.0    12477.347150  1.708059e+06  2.753900e+06  12171.435233
2.0     9239.314516  1.225675e+06  1.948344e+06   8881.766129

In [33]:
redcomm_2022 = redcomm[['month', 'period', 'like', 'comments', 'saved', 'share', 'engagement', 'video_views', 'reach', 'impression']][redcomm['year']==2022]
redcomm_2022

,month,period,like,comments,saved,share,engagement,video_views,reach,impression
318,12.0,Afternoon,1318.0,5.0,107.0,173.0,1603.0,0,195406,236441
319,12.0,Morning,12513.0,274.0,53.0,26.0,12866.0,1529,933350,1278690
320,12.0,Morning,1703.0,28.0,175.0,134.0,2040.0,0,136252,260241
321,12.0,Morning,25519.0,312.0,10.0,166.0,26007.0,0,2901341,5106360
322,12.0,Midnight,11594.0,118.0,148.0,10.0,11870.0,0,981768,1570829
...,...,...,...,...,...,...,...,...,...,...
2608,1.0,Afternoon,2446.0,37.0,188.0,54.0,2725.0,2070,607498,807972
2609,1.0,Morning,10223.0,147.0,76.0,97.0,10543.0,1114,1475764,2316949
2610,1.0,Morning,10125.0,52.0,4.0,96.0,10277.0,0,1095117,1445554
2611,1.0,Morning,24190.0,159.0,88.0,108.0,24545.0,1761,4601342,5889718
2612,1.0,Midnight,14006.0,62.0,190.0,19.0,14277.0,1454,1752248,2312967

In [50]:
# AVERAGE 2022
engage2022 = pd.DataFrame(redcomm_2022.groupby('month')[['engagement', 'reach', 'impression', 'like']].mean())
engage2022[]

         engagement         reach    impression          like
month
1.0    15103.721053  1.950112e+06  3.118233e+06  14716.439153
2.0    15597.398058  2.004992e+06  3.259757e+06  15155.252427
3.0    12645.818565  1.629543e+06  2.609922e+06  12240.974684
4.0    10647.840580  1.432260e+06  2.294290e+06  10307.492754
5.0    11032.747126  1.411297e+06  2.258609e+06  10689.241379
6.0    13678.394118  1.709555e+06  2.695086e+06  13190.247059
7.0    11068.902299  1.429866e+06  2.328617e+06  10691.701149
8.0    11309.516304  1.559980e+06  2.542156e+06  10954.603261
9.0    11632.984043  1.612501e+06  2.548923e+06  11273.170213
10.0   11172.945355  1.496843e+06  2.404119e+06  10844.841530
11.0   10848.386598  1.395710e+06  2.274348e+06  10523.051546
12.0   12288.208556  1.655818e+06  2.663042e+06  11912.272727